version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "knocklabs/product"
    versioning-strategy: increase
    open-pull-requests-limit: 5
    groups:
      telegraph-packages:
        patterns:
          - "@telegraph/*"
    ignore:
      - dependency-name: "@radix-ui/react-popover"
      - dependency-name: "@radix-ui/react-visually-hidden"
      # nanoid >3 drops support for cjs
      - dependency-name: "nanoid"
        versions: [">=4.0.0"]
      # We cannot upgrade tanstack store to >=0.7.0 at the moment until we are
      # ready to require more recent typescript version (likely v5.4 or greater)
      # See: https://github.com/knocklabs/javascript/pull/520
      - dependency-name: "@tanstack/store"
      - dependency-name: "@tanstack/react-store"
