version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "knocklabs/product"
    versioning-strategy: increase
    open-pull-requests-limit: 5
