version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    versioning-strategy: increase
    open-pull-requests-limit: 5
    groups:
      telegraph-packages:
        patterns:
          - "@telegraph/*"
    ignore:
      # nanoid >3 drops support for cjs
      - dependency-name: "nanoid"
        versions: [">=4.0.0"]
