import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { useAuth } from "../auth";
import { KNOCK_USER_ID } from "../config";
import { colors, radius, spacing } from "../theme";

export default function SignInScreen() {
  const { signIn } = useAuth();
  const [userId, setUserId] = useState(KNOCK_USER_ID);

  const canContinue = userId.trim().length > 0;

  return (
    <View style={styles.root}>
      <Text style={styles.heading}>Identify the user</Text>
      <Text style={styles.subheading}>
        Knock needs a stable user ID. In production, pair this with a signed
        user token generated by your backend.
      </Text>

      <Text style={styles.label}>User ID</Text>
      <TextInput
        value={userId}
        onChangeText={setUserId}
        autoCapitalize="none"
        autoCorrect={false}
        placeholderTextColor={colors.mutedText}
        style={styles.input}
      />

      <Pressable
        onPress={() => signIn(userId.trim())}
        disabled={!canContinue}
        style={({ pressed }) => [
          styles.button,
          !canContinue && styles.disabled,
          pressed && styles.pressed,
        ]}
      >
        <Text style={styles.buttonText}>Continue</Text>
      </Pressable>
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
    padding: spacing.lg,
    gap: spacing.md,
  },
  heading: {
    color: colors.text,
    fontSize: 26,
    fontWeight: "600",
    letterSpacing: -0.5,
  },
  subheading: {
    color: colors.mutedText,
    fontSize: 15,
    lineHeight: 22,
  },
  label: {
    color: colors.mutedText,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: spacing.md,
  },
  input: {
    color: colors.text,
    fontSize: 16,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  button: {
    marginTop: spacing.md,
    backgroundColor: colors.accent,
    paddingVertical: spacing.md,
    borderRadius: radius.md,
    alignItems: "center",
  },
  disabled: {
    opacity: 0.4,
  },
  pressed: {
    opacity: 0.8,
  },
  buttonText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "600",
  },
});
