name: CI/CD

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@knocklabs"

      - name: Install dependencies
        run: yarn --immutable

      - name: Check formatting
        run: yarn format:check

      - name: Build packages
        run: yarn build:packages

      - name: Run type check
        run: yarn type:check

      - name: Run Lint
        run: yarn lint

      - name: Run tests
        run: yarn test:ci

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: knocklabs/javascript

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
