name: Expo Build
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22.x"
          cache: yarn
          registry-url: "https://registry.npmjs.org"
          scope: "@knocklabs"
      - name: Install Dependencies
        run: yarn install
      - name: Build packages
        run: yarn build:packages
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # 8.2.1
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Build on EAS
        run: cd examples/expo-example && eas build --platform android --non-interactive
