name: Integration Tests

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: run-code-checks-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-integration-tests:
    name: Integration Tests (React ${{ matrix.react-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - react-version: "16.14.0"
          - react-version: "17.0.2"
          - react-version: "18.2.0"
          - react-version: "19.1.0"
    steps:
      - name: Checkout Latest
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
          scope: "@knocklabs"
      - name: Install Dependencies
        run: yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - name: Build Packages
        run: yarn build:packages
      - name: Setup React Version
        run: |
          jq '.resolutions += {} \
            | .resolutions["react"] = "${{ inputs.react-version }}" \
            | .resolutions["react-dom"] = "${{ inputs.react-version }}"' package.json > tmp.json
          mv tmp.json package.json
      - name: Update Dependencies For Integration Tests
        run: yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - name: Run Test
        run: yarn test:integration
