name: Integration Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-integration-tests:
    name: React ${{ matrix.react-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - react-version: "16.14.0"
            testing-library-version: "12.1.5"
          - react-version: "17.0.2"
            testing-library-version: "12.1.5"
          - react-version: "18.2.0"
          - react-version: "19.1.0"
    env:
      INTEGRATION_KNOCK_PUBLIC_KEY: ${{ secrets.INTEGRATION_KNOCK_PUBLIC_KEY }}
      INTEGRATION_KNOCK_USER_ID: ${{ secrets.INTEGRATION_KNOCK_USER_ID }}
      INTEGRATION_KNOCK_FEED_ID: ${{ secrets.INTEGRATION_KNOCK_FEED_ID }}
    steps:
      - name: Checkout Latest
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
          scope: "@knocklabs"
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build Packages
        run: yarn build:packages
      - name: Setup React Version
        run: cd integration/web && yarn add react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }}
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - name: Setup Testing Library Version
        if: matrix.testing-library-version
        run: cd integration/web && yarn add @testing-library/react@${{ matrix.testing-library-version }}
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - name: Run Test
        run: yarn test:integration
