name: Run Code Checks

on:
  workflow_call:
    inputs:
      react-version:
        required: true
        type: string
      testing-library-version:
        required: false
        type: string

concurrency:
  group: run-code-checks-${{ github.workflow }}-${{ github.ref }}-react-${{ inputs.react-version }}
  cancel-in-progress: true

jobs:
  run-code-checks:
    name: Run Code Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
          scope: "@knocklabs"
      - name: Install Dependencies
        run: yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - name: Build Packages
        run: yarn build:packages
      - name: Update React Version For Integration Tests
        run: yarn workspace @knocklabs/integration-web add react@${{ inputs.react-version }} react-dom@${{ inputs.react-version }}
      - name: Run Test
        run: yarn test:integration
