name: Run Code Checks

on:
  workflow_call:
    inputs:
      react-version:
        required: true
        type: string
      testing-library-version:
        required: false
        type: string

concurrency:
  group: run-code-checks-${{ github.workflow }}-${{ github.ref }}-react-${{ inputs.react-version }}
  cancel-in-progress: true

jobs:
  run-code-checks:
    name: Run Code Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
          scope: "@knocklabs"
      - name: Install Dependencies
        run: yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - name: Build Packages
        run: yarn build:packages
      - name: Setup React Version
      - name: Setup React Version
        run: |
          jq '.resolutions += {} \
            | .resolutions["react"] = "${{ matrix.react-version }}" \
            | .resolutions["react-dom"] = "${{ matrix.react-version }}"' package.json > tmp.json
          mv tmp.json package.json
      - name: Update Dependencies For Integration Tests
        run: yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - name: Run Test
        run: yarn test:integration
