name: Code Checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-code-checks:
    name: Run Code Checks (React ${{ matrix.react-version }})
    uses: ./.github/workflows/run-code-checks.yml
    strategy:
      matrix:
        include:
          - react-version: "16.14.0"
          - react-version: "17.0.2"
          - react-version: "18.2.0"
          - react-version: "19.1.0"
    with:
      react-version: ${{ matrix.react-version }}
